sudo: required

language: generic

services:
  - docker

env:
  global:
    - MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.defaultLogLevel=ERROR"
    - GRADLE_OPTS: "-Dorg.gradle.logging.level=quiet"
    - PKG_KAFKA_VER: 2.0
    - PKG_CONFLUENT_VER: 5.0.x

cache:
  directories:
    - "${TRAVIS_BUILD_DIR}/build-artifacts"

before_install:
  - |
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    openssl aes-256-cbc \
      -K $encrypted_15f7e9cff7d3_key \
      -iv $encrypted_15f7e9cff7d3_iv \
      -in github_cpkafka_bld_deploy_key.enc \
      -out ${SSH_FILE} -d
    chmod 600 "${SSH_FILE}" \
      && printf "%s\n" \
        "Host github.com" \
        "  IdentityFile ${SSH_FILE}" \
        "  LogLevel ERROR" >> ~/.ssh/config

script:
  - "./build"

before_deploy:
  - |
    git config --global user.email "${GIT_EMAIL}"
    git config --global user.name "${GIT_NAME}"
    export GIT_DEPLOY_TAG="v${PKG_CONFLUENT_VER}"
    git remote add upstream git@github.com:arron-green/cpkafka-schema-registry-artifact-bldr.git
    git push upstream :refs/tags/$GIT_DEPLOY_TAG || echo "remote tag doesnt exist"
    git tag -fa -m "Release ${PKG_CONFLUENT_VER}" "${GIT_DEPLOY_TAG}"
    git push upstream --tags

branches:
  except:
    - /^*-v[0-9]/

deploy:
  provider: releases
  api_key:
    secure: IFhbmnK76lNZtlKJZaxxocleFpiyaWoa0OCrpFZdOSCwnzbbMZyV+dPGWwYXhrN5W8MnHubKwwUgPJhwjM31tOhk8FRn9spAIW+cLwBKT3l2JKpo0YxczHTRnnfWtiwtPREG87000oLe39kQ74LYG+ShnsE0yhlIQw0P+pz+Uei0anIaMLD5JOP3VCWRxMVpIhI6CuQl6VLgmnvf+BoiszDMDqwkYxyXWz1Z4Zi01Fw3ggWXOYfGJyElgBDimRdHw1RJDJc6tcEXS7f7YXIQnA9SQUD4o9I9sDx1vPIweIRxrH464udNZ7C5poNc0Aer+iGOsO2K0TfvqA7Ghg9W3AhqTvnCgddhgie4fUlBOxnyRR35qKkUbGQhy8/MMyBiHkc/xqLj6iN9KEYv89aD8jzLkYyTjXDt66vS+0AtizAQRFkoer/52LmxW279Ia2YS3UflCGCViLT0m2TU79R29pteoM/aSjCIcC75iZzv11+fV3owyE8g7n8Fouog4xR1Hvj6c90mM07xviOPhxNMezqKNAR5BQz1jBEWl9LC1CeLrfxNpHcz17h9r44Yl3OjOfIAaxsD/2NYpyXKLhlf/VNfS4t2BvWK+mNNC2eWE9icrC0WspLPzW6X3YMp/sYgyzhfBvSZqyocanxJeDwDAqQmfUwPPSDs6/scVKXWIU=
  file:
    - build-artifacts/m2-artifact-repo.tgz
    - build-artifacts/pkg-common.tgz
    - build-artifacts/pkg-kafka.tgz
    - build-artifacts/pkg-ksql.tgz
    - build-artifacts/pkg-rest-utils.tgz
    - build-artifacts/pkg-schema-registry.tgz
    - build-artifacts/pkg-kafka-rest.tgz
    # - build-artifacts/pkg-.tgz
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
