sudo: required

language: generic

services:
  - docker

env:
  global:
    - MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.defaultLogLevel=WARN"
    - GRADLE_OPTS: "-Dorg.gradle.logging.level=warn"
    - ENCRYPTION_LABEL: "a341e0c086e0"
    - COMMIT_AUTHOR_EMAIL: "arrong@gmail.com"
cache:
  directories:
    - "$TRAVIS_BUILD_DIR/build-artifacts"

before_install:
  - openssl aes-256-cbc -K $encrypted_a341e0c086e0_key -iv $encrypted_a341e0c086e0_iv -in deploykey.enc -out deploykey -d
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin

script:
  - ./deploy
