#!/usr/bin/env bash
set -e

source ./env

function pull-build-push {
    local ARG=$1
    docker-compose pull ${ARG} || echo "failed to pull '${ARG}'"
    docker-compose build ${ARG}
    docker-compose push ${ARG} || echo "failed to push '${ARG}'"
}

pull-build-push base

PKG_NAME=kafka PKG_VER=${PKG_KAFKA_VER} ./kafka/prep
pull-build-push kafka

for COMPONENT in common rest-utils schema-registry kafka-rest ksql; do
    PKG_NAME=${COMPONENT} PKG_VER=${PKG_CONFLUENT_VER} ./${COMPONENT}/prep
    pull-build-push "${COMPONENT}"
done

# TODO: finish me
# case "$(uname -s)" in
#     Darwin*)    ARTIFACTS_USER=$(stat -f "%u:%g" ./build-artifacts);;
#     *)          ARTIFACTS_USER=$(stat -c "%u:%g" ./build-artifacts);;
# esac
#
# # copy build artifacts from container to host
# docker run --rm -iv${PWD}/build-artifacts:/build-artifacts --user="root" $DOCKER_TAG bash -s <<EOF
# cd /home/${DOCKER_BUILD_USER}
# chown -R ${ARTIFACTS_USER} /build-artifacts
# tar -czf /home/${DOCKER_BUILD_USER}/m2-artifact-repo.tgz /home/${DOCKER_BUILD_USER}/.m2
# chown -R "${ARTIFACTS_USER}" RELEASE.md *.tgz
# mv RELEASE.md *.tgz /build-artifacts
# EOF
