#!/usr/bin/env bash
set -ex
DOCKER_TAG=arrongreen/cpkafka-schema-registry-artifact-bldr:latest

PKG_KAFKA_VER=${PKG_KAFKA_VER-2.0}
# PKG_KAFKA_VER=${PKG_KAFKA_VER-5.0.0-beta}
PKG_CONFLUENT_VER=${PKG_CONFLUENT_VER-5.0.x}

JAVA_VER=${JAVA_VER-8.0.171-oracle}
SCALA_VER=${SCALA_VER-2.11}
GRADLE_VER=${GRADLE_VER-4.8.1}
MAVEN_VER=${MAVEN_VER-3.5.2}
AVRO_VER=${AVRO_VER-1.8.2}
GRADLE_OPTS=${GRADLE_OPTS--Xmx2048m}
MAVEN_OPTS=${MAVEN_OPTS}
DOCKER_BUILD_USER=kafkabldr

if [[ ! -e artifacts.tgz ]]; then
    curl -s -L -o artifacts.tgz https://github.com/arron-green/cpkafka-schema-registry-artifact-bldr/releases/download/v5.0.0-beta/m2-artifact-repo.tgz
fi

docker build \
    --build-arg JAVA_VER="${JAVA_VER}" \
    --build-arg SCALA_VER="${SCALA_VER}" \
    --build-arg GRADLE_VER="${GRADLE_VER}" \
    --build-arg MAVEN_VER="${MAVEN_VER}" \
    --build-arg PKG_CONFLUENT_VER="${PKG_CONFLUENT_VER}" \
    --build-arg PKG_KAFKA_VER="${PKG_KAFKA_VER}" \
    --build-arg AVRO_VER="${AVRO_VER}" \
    --build-arg MAVEN_OPTS="${MAVEN_OPTS}" \
    --build-arg GRADLE_OPTS="${GRADLE_OPTS}" \
    -t $DOCKER_TAG .

case "$(uname -s)" in
    Darwin*)    ARTIFACTS_USER=$(stat -f "%u:%g" ./build-artifacts);;
    *)          ARTIFACTS_USER=$(stat -c "%u:%g" ./build-artifacts);;
esac

# copy build artifacts from container to host
docker run --rm -iv${PWD}/build-artifacts:/build-artifacts --user="root" $DOCKER_TAG bash -s <<EOF
cd /home/${DOCKER_BUILD_USER}
chown -R ${ARTIFACTS_USER} /build-artifacts
tar -czf /home/${DOCKER_BUILD_USER}/m2-artifact-repo.tgz /home/${DOCKER_BUILD_USER}/.m2
chown -R "${ARTIFACTS_USER}" *.tgz
mv *.tgz /build-artifacts
EOF
