#!/usr/bin/env bash
set -x
source $SDKMAN_DIR/bin/sdkman-init.sh

cd "$HOME" && (curl -L https://github.com/confluentinc/common/archive/${PKG_CONFLUENT_VER}.tar.gz | tar -zx)

cd "$HOME/common-${PKG_CONFLUENT_VER}"
mvn -Dmaven.test.skip=$MAVEN_SKIP_TESTS clean package install

# package common
cd package/target
tar -czvf $HOME/common-package-${PKG_CONFLUENT_VER}.tgz \
    common-*
