#!/usr/bin/env bash
set -ex
source ${SDKMAN_DIR}/bin/sdkman-init.sh &> /dev/null
PKG_NAME=kafka
cd "${HOME}" && (curl -s -L https://github.com/confluentinc/${PKG_NAME}/archive/${PKG_KAFKA_VER}.tar.gz | tar -zx)

cd "${HOME}/${PKG_NAME}-${PKG_KAFKA_VER}"
gradle installAll releaseTarGz -x signArchives

tar -czf ${HOME}/pkg-${PKG_NAME}.tgz *
