#!/usr/bin/env bash
set -ex
source ${SDKMAN_DIR}/bin/sdkman-init.sh &> /dev/null
PKG_NAME=kafka-rest
cd "${HOME}" && (curl -s -L https://github.com/confluentinc/${PKG_NAME}/archive/${PKG_CONFLUENT_VER}.tar.gz | tar -zx)

cd "${HOME}/${PKG_NAME}-${PKG_CONFLUENT_VER}"
BUILD_OPTS="-Davro.version=${AVRO_VER} -Dmaven.test.skip=${MAVEN_SKIP_TESTS}"
mvn ${MAVEN_OPTS} ${BUILD_OPTS} -q clean install
mvn ${MAVEN_OPTS} ${BUILD_OPTS} -q package \
tar -czf ${HOME}/pkg-${PKG_NAME}.tgz *
