#!/usr/bin/env bash
set -x
source $SDKMAN_DIR/bin/sdkman-init.sh
PKG_NAME=kafka-rest
cd "$HOME" && (curl -L https://github.com/confluentinc/${PKG_NAME}/archive/${PKG_CONFLUENT_VER}.tar.gz | tar -zx)

cd "$HOME/${PKG_NAME}-${PKG_CONFLUENT_VER}"
mvn -Davro.version=$AVRO_VER -Dmaven.test.skip=$MAVEN_SKIP_TESTS clean package install

tar -czvf ${HOME}/pkg-${PKG_NAME}.tgz *
