#!/usr/bin/env bash
set -ex
source ${SDKMAN_DIR}/bin/sdkman-init.sh &> /dev/null
PKG_NAME=ksql
cd "${HOME}" && (curl -s -L https://github.com/confluentinc/${PKG_NAME}/archive/${PKG_CONFLUENT_VER}.tar.gz | tar -zx)

cd "${HOME}/${PKG_NAME}-${PKG_CONFLUENT_VER}"
BUILD_OPTS="-Davro.version=${AVRO_VER} -Dmaven.test.skip=${MAVEN_SKIP_TESTS}"
mvn clean
for MODULE in ksql-common ksql-metastore ksql-engine; do
    mvn ${MAVEN_OPTS} -q test install -pl ${MODULE} -am
done
mvn ${MAVEN_OPTS} ${BUILD_OPTS} -q install package
tar -czf ${HOME}/pkg-${PKG_NAME}.tgz *
