#!/usr/bin/env bash
set -ex
source ${SDKMAN_DIR}/bin/sdkman-init.sh
PKG_NAME=ksql
cd "${HOME}" && (curl -L https://github.com/confluentinc/${PKG_NAME}/archive/${PKG_CONFLUENT_VER}.tar.gz | tar -zx)

cd "${HOME}/${PKG_NAME}-${PKG_CONFLUENT_VER}"
# BUILD_OPTS="-Davro.version=$AVRO_VER -Dkafka.scala.version=$SCALA_VER -Dmaven.test.skip=$MAVEN_SKIP_TESTS"
BUILD_OPTS="-Davro.version=${AVRO_VER} -Dmaven.test.skip=${MAVEN_SKIP_TESTS}"
mvn clean
for MODULE in ksql-common ksql-metastore ksql-engine; do
    mvn ${MAVEN_OPTS} test install -pl ${MODULE} -am
done
mvn ${MAVEN_OPTS} ${BUILD_OPTS} install package
# mvn $BUILD_OPTS package
# find . -name \*target\*
tar -czf ${HOME}/pkg-${PKG_NAME}.tgz *
