#!/usr/bin/env bash
set -ex
source ${SDKMAN_DIR}/bin/sdkman-init.sh &> /dev/null

for PKG in java gradle maven; do
    PKG_VER_ENV_KEY=$(printf "%s_VER" "$(echo ${PKG} | tr a-z A-Z)")
    PKG_VER="$(printenv "${PKG_VER_ENV_KEY}")"
    echo "installing sdk '${PKG}' with version '${PKG_VER}'"
    sdk install "${PKG}" "${PKG_VER}" &> /dev/null
done
